const K='md2a061',$=x=>document.getElementById(x),C=MD2.classes;
function mk(n='Héroe',c='rogue'){let x=C[c];return{id:Date.now()+Math.random(),name:n,cls:c,level:1,xp:0,hp:x.hp,hpMax:x.hp,mana:x.mana,manaMax:x.mana,zone:'light',actions:3,choices:{1:null},move:{on:false,pm:0},inventory:[],equipped:[],rogue:{hand:3,spent:0},shaman:{fire:0,water:0,air:0,nature:0,unlocked:{}},paladin:{consecrations:0,blessed:''},mage:{amulet:0},berserker:{fury:0,stance:'Furia Sangrienta'}}}
function fresh(){return{round:1,phase:0,phaseHist:[],dark:{side:'front',i:0},heroes:[mk('Pícaro')],active:0,history:[],xpHist:[],voice:'yes',rate:1}}
let s=JSON.parse(localStorage.getItem(K)||'null')||fresh(),h=()=>s.heroes[s.active],cl=()=>C[h().cls],save=()=>localStorage.setItem(K,JSON.stringify(s));
function say(t){if(s.voice!=='yes'||!speechSynthesis)return;speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.lang='es-ES';u.rate=+s.rate||1;speechSynthesis.speak(u)}
function log(t){s.history.unshift({r:s.round,p:MD2.phases[s.phase],n:h()?.name||'Grupo',t});save();hist()}
function dungeon(){return Math.max(...s.heroes.map(x=>x.level),1)}
function sk(){return cl().skills.map(x=>({name:x[0],level:x[1],branch:x[2],grade:x[3]}))}
function actSkills(){let a=Object.values(h().choices||{}).filter(Boolean).map(n=>sk().find(x=>x.name===n)).filter(Boolean),b={};a.forEach(x=>{if(!b[x.branch]||x.grade>b[x.branch].grade)b[x.branch]=x});return Object.values(b)}
function pendingSkill(x=h()){for(let n=1;n<=x.level;n++)if(!x.choices?.[n])return true;return false}
function ensureSkillChosen(){if(pendingSkill()){alert('Debes escoger la habilidad pendiente antes de comenzar o continuar el turno.');tab('skills');return false}return true}
function attackRelevant(name){let s=name.toLowerCase();return ['ataque','flecha','tormenta','avalancha','surco','magia oscura','audacia','desterrar','furia letal','carga','revancha','mixtura','forma sombría','volea','perforante','incendiaria','mago de batalla'].some(k=>s.includes(k))}
function defenseRelevant(name){let s=name.toLowerCase();return ['defensa','vínculo','vinculo','armadura','revancha','provocador','audacia'].some(k=>s.includes(k))}
function actionsSpeech(){let a=h().actions;say(a===0?'No quedan acciones. Puedes finalizar el turno.':a===1?'Te queda 1 acción.':`Te quedan ${a} acciones.`)}

function darkArr(){return MD2.darkness[s.dark.side]} function darkNow(){return darkArr()[s.dark.i]}
function phaseHelp(){return['Cada héroe dispone de 3 acciones.','Activa las cuadrillas y después los errantes.','Los héroes con XP suficiente pueden subir.','Avanza el medidor y resuelve el efecto.'][s.phase]}
function render(){ $('round').textContent=s.round;$('phase').textContent=MD2.phases[s.phase];$('phaseChip').textContent=MD2.phases[s.phase];$('dungeon').textContent=dungeon();$('darkPos').textContent=darkNow()[0];$('phaseHelp').textContent=phaseHelp();roster();darkness();hero();hist();inventory();$('voice').value=s.voice;$('rate').value=s.rate;shotVis()}
function roster(){$('roster').innerHTML=s.heroes.map((x,i)=>`<div class="heroCard ${i===s.active?'active':''}" data-hi="${i}"><b>${x.name}</b> · ${C[x.cls].label} · Nivel ${x.level}<br><small>XP ${x.xp} · Vida ${x.hp}/${x.hpMax} · Maná ${x.mana}/${x.manaMax}</small></div>`).join('');document.querySelectorAll('[data-hi]').forEach(e=>e.onclick=()=>{s.active=+e.dataset.hi;save();render();tab('hero')})}
function darkness(){let a=darkArr();$('darkTrack').innerHTML=a.map((x,i)=>`<div class="cell ${i===s.dark.i?'active':''}">${x[0]}</div>`).join('');$('darkEvent').textContent=`${s.dark.side==='front'?'Anverso':'Reverso'} · ${darkNow()[0]}: ${darkNow()[1]}`}
function hero(){let x=h();$('heroSelect').innerHTML=s.heroes.map((q,i)=>`<option value="${i}" ${i===s.active?'selected':''}>${q.name}</option>`).join('');$('heroClass').innerHTML=Object.keys(C).map(k=>`<option value="${k}" ${k===x.cls?'selected':''}>${C[k].label}</option>`).join('');$('heroName').value=x.name;$('level').textContent=x.level;$('xp').textContent=x.xp;$('actionsLeft').textContent=x.actions;$('hp').textContent=x.hp;$('hpMax').textContent=x.hpMax;$('mana').textContent=x.mana;$('manaMax').textContent=x.manaMax;$('zone').textContent=x.zone==='dark'?'Oscuridad':'Luz';$('pendingSkill').textContent=pendingSkill(x)?'Sí':'No';$('pendingSkill').parentElement.classList.toggle('pending',pendingSkill(x));$('baseAbilities').innerHTML=`<div class="passive"><b>Habilidad propia</b><br><small>${cl().ability}</small></div><div class="passive"><b>Sombras</b><br><small>${cl().shadow}</small></div>`;classPanel();choices();tree();moveRender()}
function classPanel(){let x=h(),z='';
if(x.cls==='rogue')z=`<div class="resource"><b>Fichas</b><p>Mano: ${x.rogue.hand} · Gastadas: ${x.rogue.spent}</p><div class="row"><button id="rDraw">Robar ficha</button><button id="rSpend">Gastar ficha</button></div></div><div class="passive"><b>Sombras</b><br><small>Al atacar con ficha de Sombras, estás en las Sombras.</small></div><div class="passive"><b>Veneno</b><br><small>1 ficha máxima por enemigo; vuelve a la bolsa cuando muere.</small></div>`;
if(x.cls==='ranger')z=`<div class="resource"><b>Mazo de Flechas</b><p>Resuélvelo físicamente: Rápido, Certero o Fallido.</p></div>`;
if(x.cls==='shaman')z=`<div class="resource"><b>Elementos</b>${['fire','water','air','nature'].map(k=>`<div class="row"><span class="badge">${{fire:'🔥 Fuego',water:'💧 Agua',air:'💨 Aire',nature:'🌿 Naturaleza'}[k]} ${x.shaman[k]}/4</span><button data-el="${k}" data-d="-1">−</button><button data-el="${k}" data-d="1">+</button><button data-max="${k}">Máx.</button><button data-use="${k}" ${x.shaman.unlocked[k]?'disabled':''}>${x.shaman.unlocked[k]?'Desbloqueada':'Consumir'}</button></div>`).join('')}</div><div class="resource"><b>Bendiciones permanentes</b>${Object.keys(MD2.shamanBlessings).map(k=>`<div class="passive ${x.shaman.unlocked[k]?'blessingActive':'locked'}"><b>${x.shaman.unlocked[k]?'✓ ':'🔒 '}${MD2.shamanBlessings[k].name}</b><br><small>${MD2.shamanBlessings[k].effect}</small></div>`).join('')}</div>`;
if(x.cls==='paladin')z=`<div class="resource"><b>Consagraciones: ${x.paladin.consecrations}</b><div class="row"><button id="conAdd">Consagrar (−1 maná)</button><button id="conRem">Retirar</button></div><small>El jugador comprueba LdV y que no exista otra ficha.</small></div><div class="resource"><label>Habilidad bendecida<select id="blessed"><option value="">Ninguna</option>${actSkills().map(q=>`<option ${x.paladin.blessed===q.name?'selected':''}>${q.name}</option>`).join('')}</select></label></div>`;
if(x.cls==='mage')z=`<div class="resource"><b>Amuleto Mágico</b><p class="notice">${['+1 Espada','+1 Alcance','+1 PM','Cura 3'][x.mage.amulet]}</p><button id="amulet">Girar</button></div>`;
if(x.cls==='berserker')z=`<div class="resource"><b>Furia ${x.berserker.fury}/7</b><div class="row"><button id="fDown">−</button><button id="fUp">+</button></div></div><div class="resource"><label>Postura<select id="stance"><option>Furia Sangrienta</option><option>Temerario</option><option>Provocador</option></select></label></div><p class="notice">Las fichas de vida perdidas pueden convertirse en Furia. Máximo 7.</p>`;
$('classPanel').innerHTML=z;bindClass()}
function bindClass(){let x=h();if(x.cls==='rogue'){$('rDraw').onclick=()=>{x.rogue.hand++;x.actions++;log('Robó ficha y ganó 1 acción.');render()};$('rSpend').onclick=()=>{if(!x.rogue.hand)return alert('Sin fichas');x.rogue.hand--;x.rogue.spent++;log('Gastó una ficha.');render()}}
if(x.cls==='shaman'){document.querySelectorAll('[data-el]').forEach(b=>b.onclick=()=>{let k=b.dataset.el;x.shaman[k]=Math.max(0,Math.min(4,x.shaman[k]+ +b.dataset.d));save();render()});document.querySelectorAll('[data-max]').forEach(b=>b.onclick=()=>{x.shaman[b.dataset.max]=4;save();render();say('Elemento al máximo. Puedes consumirlo.')});document.querySelectorAll('[data-use]').forEach(b=>b.onclick=()=>{let k=b.dataset.use;if(x.shaman.unlocked[k])return alert('Esta bendición ya está activa permanentemente.');if(x.shaman[k]<4)return alert('No está al máximo');x.shaman[k]=0;x.shaman.unlocked[k]=true;log(`Consumió ${k} y activó permanentemente ${MD2.shamanBlessings[k].name}.`);render();say(`${MD2.shamanBlessings[k].name} activa durante toda la misión.`)})}
if(x.cls==='paladin'){$('conAdd').onclick=()=>{if(x.mana<1)return alert('Necesitas 1 maná');x.mana--;x.paladin.consecrations++;log('Colocó Consagración.');render()};$('conRem').onclick=()=>{x.paladin.consecrations=Math.max(0,x.paladin.consecrations-1);log('Retiró Consagración.');render()};$('blessed').onchange=e=>{x.paladin.blessed=e.target.value;save()}}
if(x.cls==='mage')$('amulet').onclick=()=>{x.mage.amulet=(x.mage.amulet+1)%4;log('Giró el Amuleto.');render()};
if(x.cls==='berserker'){$('fDown').onclick=()=>{x.berserker.fury=Math.max(0,x.berserker.fury-1);save();render()};$('fUp').onclick=()=>{x.berserker.fury=Math.min(7,x.berserker.fury+1);save();render()};$('stance').value=x.berserker.stance;$('stance').onchange=e=>{x.berserker.stance=e.target.value;log(`Postura: ${e.target.value}.`);render()}}}
function choices(){let x=h(),a=sk(),o='';for(let n=1;n<=x.level;n++)o+=`<label class="top">Elección nivel ${n}<select data-choice="${n}"><option value="">Sin elegir</option>${a.filter(q=>q.level<=n).map(q=>`<option value="${q.name}" ${x.choices[n]===q.name?'selected':''}>${q.name}</option>`).join('')}</select></label>`;o+=`<p class="notice"><b>Activas:</b> ${actSkills().map(q=>`<span class="badge">${q.name}</span>`).join(' ')||'Ninguna'}</p>`;$('skillChoices').innerHTML=o;document.querySelectorAll('[data-choice]').forEach(e=>e.onchange=()=>{let n=+e.dataset.choice,v=e.value||null;if(v){let q=a.find(z=>z.name===v),higher=actSkills().find(z=>z.branch===q.branch&&z.grade>q.grade);if(higher){alert(`Ya tienes ${higher.name}`);e.value=x.choices[n]||'';return}}x.choices[n]=v;save();choices();tree()})}
function tree(){let x=h(),a=sk(),ac=new Set(actSkills().map(q=>q.name)),o='';for(let n=1;n<=5;n++){let lock=n>x.level;o+=`<button class="levelHeader" data-l="${n}" ${lock?'disabled':''}>Nivel ${n} ${lock?'🔒':''}</button><div id="l${n}" class="levelBody">${a.filter(q=>q.level===n).map(q=>`<div class="skill ${lock?'locked':''}"><b>${q.name}</b><br><small>${ac.has(q.name)?'Activa':'Referencia'}</small></div>`).join('')}</div>`}$('skillTree').innerHTML=o;document.querySelectorAll('[data-l]').forEach(b=>{if(!b.disabled)b.onclick=()=>$('l'+b.dataset.l).classList.toggle('hidden')})}
function hist(){$('history').innerHTML=s.history.length?s.history.map(x=>`<div><b>Ronda ${x.r} · ${x.p} · ${x.n}</b><br>${x.t}</div>`).join(''):'<p class="muted">Sin registros.</p>'}
function inventory(){let x=h();$('inventory').innerHTML=[...x.equipped.map(q=>`<div class="inventoryItem"><b>Equipado:</b> ${q}</div>`),...x.inventory.map(q=>`<div class="inventoryItem"><b>Inventario:</b> ${q}</div>`)].join('')||'<p class="muted">Sin objetos.</p>'}
function advanceDark(voice=true){if(s.dark.side==='front'){if(s.dark.i<8)s.dark.i++;else{s.dark.side='back';s.dark.i=0}}else s.dark.i=(s.dark.i+1)%4;let t=`Oscuridad ${darkNow()[0]}. ${darkNow()[1]}`;log(t);if(voice)say(t);darkness()}
function nextPhase(){s.phaseHist.push({p:s.phase,r:s.round,d:{...s.dark}});if(s.phase<3)s.phase++;else{advanceDark(false);s.phase=0;s.round++;s.heroes.forEach(x=>x.actions=3)}log(`Comienza ${MD2.phases[s.phase]}.`);render();say(phaseHelp())}
function xp(kind){let before=s.heroes.map(x=>x.xp);if(kind==='m')h().xp++;if(kind==='l')s.heroes.forEach(x=>x.xp+=2);if(kind==='r')s.heroes.forEach(x=>x.xp+=4);s.xpHist.push(before);log(kind==='m'?`${h().name} gana 1 XP.`:kind==='l'?'Todo el grupo gana 2 XP.':'Todo el grupo gana 4 XP.');render()}
function up(){let x=h();if(s.phase!==2)return alert('Solo en fase de Subida de nivel');if(x.level>=5)return alert('Nivel máximo');let cost=MD2.levelCosts[x.level];if(x.xp<cost)return alert(`Necesitas ${cost} XP`);x.xp-=cost;x.level++;let g=MD2.levelGains[x.level];x.hpMax+=g.hp;x.hp+=g.hp;x.manaMax+=g.mana;x.mana+=g.mana;x.choices[x.level]=null;let t=`Sube a nivel ${x.level}. Vida +${g.hp}, maná +${g.mana}. ${g.treasure} Debes elegir una habilidad antes de continuar.`;log(t);$('levelInfo').textContent=t;render();say(t)}
function spend(a){let x=h();if(!ensureSkillChosen())return false;if(s.phase!==0)return alert('Solo en fase de Héroes');if(x.actions<=0)return alert('Sin acciones');if(x.cls==='rogue'){if(!x.rogue.hand)return alert('Sin fichas');if(!confirm(`Gastar ficha para ${a}?`))return;x.rogue.hand--;x.rogue.spent++}x.actions--;log(`${a}: −1 acción.`);render();actionsSpeech();return true}
function moveStart(){if(spend('Movimiento')===false)return false;let x=h();x.move={on:true,pm:(x.cls==='ranger'?3:2)+(x.cls==='shaman'&&x.shaman.unlocked.air?1:0)};log(`Movimiento con ${x.move.pm} PM.`);render()}
function moveRender(){let x=h();$('movePm').textContent=x.move.pm||0;document.querySelectorAll('[data-move]').forEach(b=>b.disabled=!(x.move.on&&x.move.pm>0))}
function moveUse(k){let x=h();if(!x.move.on||!x.move.pm)return;x.move.pm--;log(k==='move'?'Se movió 1 zona.':k==='door'?'Abrió una puerta.':'Interactuó.');if(!x.move.pm)x.move.on=false;render()}
function shotVis(){$('shotBox').classList.toggle('hidden',!(h().cls==='ranger'&&$('attackType').value==='A distancia'))}
function resetAttack(){['s1','s2','s3','s4'].forEach((x,i)=>$(x).classList.toggle('active',i===0));$('effects').textContent='Confirma primero la reserva.';$('damageResult').textContent=''}
function pool(){let x=h(),a=[`Reserva: ${$('heroDice').value||'no indicada'}.`],b=+$('blackDice').value||0,m=+$('minions').value||0;if(x.zone==='dark')a.push('Añade dado de Oscuridad y revisa Sombras.');if(!m&&b)a.push('Sin secuaces: revisa si corresponden dados negros.');else if(b)a.push(`${b} dado(s) negro(s).`);if(x.cls==='ranger'&&$('attackType').value==='A distancia')a.push({fast:'Tiro rápido: fila central.',perfect:'Tiro certero: fila superior.',failed:'Tiro fallido: fila inferior.'}[$('shot').value]);actSkills().filter(q=>attackRelevant(q.name)).forEach(q=>a.push(`Habilidad de ataque disponible: ${q.name}.`));if(x.cls==='rogue')a.push('Puedes gastar 1 maná para relanzar 1 dado.');if(x.cls==='shaman'){Object.keys(MD2.shamanBlessings).filter(k=>x.shaman.unlocked[k]&&['fire','water'].includes(k)).forEach(k=>a.push(`${MD2.shamanBlessings[k].name}: ${MD2.shamanBlessings[k].effect}`));}if(x.zone==='dark')a.push(`Sombras del héroe: ${cl().shadow}`);$('effects').innerHTML='<ol>'+a.map(q=>`<li>${q}</li>`).join('')+'</ol>';$('s1').classList.remove('active');$('s2').classList.add('active');say('Reserva confirmada. Lanza los dados.')}

function resetDefense(){['d1','d2','d3','d4'].forEach((x,i)=>$(x).classList.toggle('active',i===0));$('defenseEffects').textContent='Confirma primero la reserva defensiva.';$('defenseResult').textContent=''}
function confirmDefense(){let x=h(),a=[`Reserva defensiva: ${$('blueDice').value||'no indicada'}.`,`Espadas enemigas: ${+$('enemySwords').value||0}.`,`Garras: ${+$('enemyClaws').value||0}.`];actSkills().filter(q=>defenseRelevant(q.name)).forEach(q=>a.push(`Habilidad defensiva disponible: ${q.name}.`));if(x.cls==='paladin')a.push('Habilidad propia: ignora 1 Garra en cada ataque.');if(x.cls==='berserker'){a.push(`Postura actual: ${x.berserker.stance}.`);a.push(`Furia disponible: ${x.berserker.fury}.`)}if(x.cls==='mage')a.push('Revisa si hay Armadura de Hielo activa.');$('defenseEffects').innerHTML='<ol>'+a.map(q=>`<li>${q}</li>`).join('')+'</ol>';$('d1').classList.remove('active');$('d2').classList.add('active');say('Reserva defensiva confirmada. Lanza los dados azules.')}
function calculateDefense(){let x=h(),w=Math.max(0,(+$('enemySwords').value||0)-(+$('defenseShields').value||0));x.hp=Math.max(0,x.hp-w);let txt=`Recibes ${w} herida(s).`;if(x.cls==='berserker'&&w>0){let room=7-x.berserker.fury,gain=Math.min(w,room);if(gain>0&&confirm(`¿Convertir ${gain} ficha(s) de vida perdida en Furia?`)){x.berserker.fury+=gain;txt+=` Ganas ${gain} Furia.`}}$('defenseResult').textContent=txt;log(`Defensa resuelta: ${txt}`);render();say(txt)}

function rule(q){q=q.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
let x=h(),cost=MD2.levelCosts[x.level];
if(q.includes('accion')&&q.includes('habilidad'))return'Una habilidad solo consume una acción adicional si su texto indica expresamente Acción. Si se activa durante Ataque, Defensa o Movimiento, forma parte de esa acción.';
if(q.includes('ataque')&&(q.includes('orden')||q.includes('resolver')))return'Orden del ataque: 1) formar reserva; 2) lanzar dados; 3) aplicar habilidades y efectos, incluidos dados negros; 4) sumar espadas y restar escudos.';
if(q.includes('defensa')||q.includes('dados azules'))return'En defensa forma la reserva de dados azules, lánzalos, aplica habilidades y efectos, y resta los escudos a las espadas enemigas. Las heridas restantes se aplican al héroe.';
if(q.includes('movimiento')||q.includes(' pm')||q.startsWith('pm'))return'Una Acción de Movimiento entrega 2 PM. El Explorador obtiene +1 PM. Cada PM permite moverse una zona, abrir una puerta o interactuar con un objeto.';
if(q.includes('oscuridad')||q.includes('sombras'))return`En oscuridad añade el dado de Oscuridad. Sombras de ${x.name}: ${C[x.cls].shadow}`;
if(q.includes('subir')&&q.includes('nivel'))return cost?`${x.name} está en nivel ${x.level}, tiene ${x.xp} XP y necesita ${cost} XP. Solo puede subir durante la fase de Subida de nivel.`:'El héroe ya está en nivel máximo.';
if(q.includes('experiencia')||q.includes(' xp'))return'Secuaz: +1 XP solo al héroe que lo elimina. Líder: +2 XP a cada héroe. Errante: +4 XP a cada héroe.';
if(q.includes('furia'))return'La Furia se obtiene moviendo fichas de vida perdidas a la reserva. El máximo es 7; el exceso se pierde. Los corazones en llamas representan Furia.';
if(q.includes('consagr'))return'Consagrar cuesta 1 maná. El jugador comprueba físicamente la LdV y que la zona no tenga otra ficha de Consagración.';
if(q.includes('elemento')||q.includes('bendicion')||q.includes('chaman'))return'Cuando un elemento del Chamán alcanza el máximo puede consumirse una vez para activar su bendición permanentemente durante la misión. El elemento vuelve a 0.';
if(q.includes('flecha')||q.includes('explorador'))return'El Explorador resuelve físicamente el mazo: menos de 7 es Rápido, exactamente 7 es Certero y más de 7 es Fallido.';
if(q.includes('picaro')||q.includes('ficha'))return'El Pícaro roba 3 fichas al inicio del turno y debe gastar una por cada acción, aunque la bonificación no corresponda a esa acción.';
if(q.includes('heroe')||q.includes('habilidad propia'))return`${x.name}, ${C[x.cls].label}. Habilidad propia: ${C[x.cls].ability} Sombras: ${C[x.cls].shadow}`;
return'No encontré una coincidencia exacta. Prueba indicando el nombre de la habilidad o usa los accesos rápidos de Ataque, Defensa, Movimiento, Oscuridad, Experiencia o Héroe activo.'}
function tab(id){document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===id));scrollTo(0,0)}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>tab(b.dataset.tab));
$('nextPhase').onclick=nextPhase;$('undoPhase').onclick=()=>{let x=s.phaseHist.pop();if(!x)return;s.phase=x.p;s.round=x.r;s.dark=x.d;render()};$('advanceDark').onclick=()=>advanceDark();$('rewindDark').onclick=()=>{if(s.dark.side==='back'&&s.dark.i===0){s.dark.side='front';s.dark.i=8}else s.dark.i=Math.max(0,s.dark.i-1);render();save()};
$('minionXp').onclick=()=>xp('m');$('leaderXp').onclick=()=>xp('l');$('roamerXp').onclick=()=>xp('r');$('undoXp').onclick=()=>{let a=s.xpHist.pop();if(a)s.heroes.forEach((x,i)=>x.xp=a[i]);render();save()};
$('addHero').onclick=()=>{s.heroes.push(mk('Nuevo héroe'));s.active=s.heroes.length-1;save();render();tab('hero')};$('deleteHero').onclick=()=>{if(s.heroes.length===1)return alert('Debe quedar un héroe');if(confirm('¿Eliminar?')){s.heroes.splice(s.active,1);s.active=0;render();save()}};
$('heroSelect').onchange=e=>{s.active=+e.target.value;render();save()};$('heroName').onchange=e=>{h().name=e.target.value||'Héroe';render();save()};$('heroClass').onchange=e=>{let n=h().name;s.heroes[s.active]=mk(n,e.target.value);render();save()};
$('hpDown').onclick=()=>{h().hp=Math.max(0,h().hp-1);render();save()};$('hpUp').onclick=()=>{h().hp=Math.min(h().hpMax,h().hp+1);render();save()};$('manaDown').onclick=()=>{h().mana=Math.max(0,h().mana-1);render();save()};$('manaUp').onclick=()=>{h().mana=Math.min(h().manaMax,h().mana+1);render();save()};
$('toggleZone').onclick=()=>{h().zone=h().zone==='dark'?'light':'dark';log(`Zona: ${h().zone==='dark'?'Oscuridad':'Luz'}.`);render();if(h().zone==='dark')say('No olvides usar el dado de Oscuridad y revisar Sombras.')};
document.querySelectorAll('[data-xp]').forEach(b=>b.onclick=()=>{h().xp=Math.max(0,h().xp+ +b.dataset.xp);render();save()});$('levelUp').onclick=up;
$('moveAction').onclick=()=>{if(moveStart()!==false)tab('actions')};$('attackAction').onclick=()=>{if(spend('Ataque')!==false){resetAttack();tab('actions');setTimeout(()=>document.getElementById('s1').scrollIntoView({behavior:'smooth'}),50)}};$('defenseAction').onclick=()=>{if(!ensureSkillChosen())return;resetDefense();tab('actions');setTimeout(()=>document.getElementById('d1').scrollIntoView({behavior:'smooth'}),50)};document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>spend(b.dataset.action));$('finishTurn').onclick=()=>{if(!ensureSkillChosen())return;h().actions=0;render();save();say('Turno finalizado.')};
document.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>moveUse(b.dataset.move));$('finishMove').onclick=()=>{h().move={on:false,pm:0};render();save()};
$('defenseAction').onclick=()=>{if(!ensureSkillChosen())return;resetDefense();tab('actions');setTimeout(()=>document.getElementById('d1').scrollIntoView({behavior:'smooth'}),50)};$('confirmDefense').onclick=confirmDefense;$('defenseRolled').onclick=()=>{$('d2').classList.remove('active');$('d3').classList.add('active');say('Aplica habilidades y efectos defensivos.')};$('defenseEffectsDone').onclick=()=>{$('d3').classList.remove('active');$('d4').classList.add('active');say('Introduce los escudos obtenidos.')};$('calculateDefense').onclick=calculateDefense;document.querySelectorAll('[data-topic]').forEach(b=>b.onclick=()=>{$('question').value=b.dataset.topic;$('ask').click()});$('attackType').onchange=shotVis;$('confirmPool').onclick=pool;$('rolled').onclick=()=>{$('s2').classList.remove('active');$('s3').classList.add('active');say('Aplica habilidades y efectos.')};$('effectsDone').onclick=()=>{$('s3').classList.remove('active');$('s4').classList.add('active');say('Suma espadas y resta escudos.')};$('damage').onclick=()=>{let d=Math.max(0,(+$('swords').value||0)-(+$('shields').value||0));$('damageResult').innerHTML=`<b>${d} herida(s).</b>`;log(`Ataque: ${d} heridas.`);say(`${d} heridas.`)};
$('addItem').onclick=()=>{let n=$('itemName').value.trim();if(!n)return;($('itemDest').value==='equip'?h().equipped:h().inventory).push(n);$('itemName').value='';inventory();save()};$('clearHistory').onclick=()=>{s.history=[];hist();save()};
$('ask').onclick=()=>{window.ans=rule($('question').value);$('answer').textContent=window.ans};$('read').onclick=()=>say(window.ans||$('answer').textContent);$('dictate').onclick=()=>{let R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return alert('Dictado no disponible');let r=new R();r.lang='es-ES';r.onresult=e=>{$('question').value=e.results[0][0].transcript;$('ask').click()};r.start()};
$('voice').onchange=e=>{s.voice=e.target.value;save()};$('rate').onchange=e=>{s.rate=e.target.value;save()};$('testVoice').onclick=()=>say(`Ronda ${s.round}. Fase ${MD2.phases[s.phase]}.`);$('export').onclick=()=>{let b=new Blob([JSON.stringify(s,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='md2_alpha06.json';a.click()};$('import').onchange=e=>{let f=e.target.files[0],r=new FileReader();r.onload=()=>{try{s=JSON.parse(r.result);save();render()}catch{alert('Archivo no válido')}};if(f)r.readAsText(f)};$('newGame').onclick=()=>{if(confirm('¿Nueva partida?')){s=fresh();save();render()}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});render();resetAttack();resetDefense();