const KEY='md2a071', $=id=>document.getElementById(id), C=MD2.classes;
const COLORS={rogue:'#8b5cf6',ranger:'#22c55e',shaman:'#f59e0b',paladin:'#3b82f6',mage:'#06b6d4',berserker:'#ef4444'};
function makeHero(cls='rogue'){const c=C[cls];return{id:Date.now()+Math.random(),name:c.label,cls,level:1,xp:0,hp:c.hp,hpMax:c.hp,mana:c.mana,manaMax:c.mana,zone:'light',actions:3,choices:{1:null},lockedChoices:{},move:{on:false,pm:0},inventory:[],equipped:[],rogue:{hand:3,spent:0},shaman:{fire:0,water:0,air:0,nature:0,unlocked:{}},paladin:{consecrations:0,blessed:''},mage:{amulet:0,slots:['+1 Espada','+1 Alcance','+1 PM','Cura 3']},berserker:{fury:0,stance:'Furia Sangrienta'}}}
function fresh(){return{round:1,phase:0,dark:{side:'front',i:0},heroes:[],active:0,history:[],phaseHistory:[],xpHistory:[],confirmed:false,voice:'yes',rate:1}}
let s=JSON.parse(localStorage.getItem(KEY)||'null')||fresh();
const h=()=>s.heroes[s.active], cl=()=>C[h().cls], save=()=>localStorage.setItem(KEY,JSON.stringify(s));
function say(t){if(s.voice!=='yes'||!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='es-ES';u.rate=+s.rate||1;speechSynthesis.speak(u)}
function log(t){s.history.unshift({r:s.round,p:MD2.phases[s.phase],n:h()?.name||'Grupo',t});save();renderHistory()}
function dungeon(){return Math.max(1,...s.heroes.map(x=>x.level))}
function skills(x=h()){return C[x.cls].skills.map(a=>({name:a[0],level:a[1],branch:a[2],grade:a[3]}))}
function activeSkills(x=h()){const chosen=Object.values(x.choices||{}).filter(Boolean).map(n=>skills(x).find(q=>q.name===n)).filter(Boolean),m={};chosen.forEach(q=>{if(!m[q.branch]||q.grade>m[q.branch].grade)m[q.branch]=q});return Object.values(m)}
function pending(x){for(let i=1;i<=x.level;i++)if(!x.lockedChoices?.[i])return i;return 0}
function darkArr(){return MD2.darkness[s.dark.side]} function darkNow(){return darkArr()[s.dark.i]}
function phaseHelp(){return['Cada héroe dispone de 3 acciones.','Activa las cuadrillas y después los monstruos errantes.','Los héroes con XP suficiente pueden subir de nivel.','Avanza el medidor y resuelve su efecto.'][s.phase]}
function heroTabName(x){return `${x.name} · ${C[x.cls].label}`}
function tab(id){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));renderHeroTabs();scrollTo(0,0)}
function render(){renderTabs();renderSetup();renderGame();renderHero();renderHistory();$('voice').value=s.voice;$('rate').value=s.rate}
function renderTabs(){renderHeroTabs();$('phaseChip').textContent=s.confirmed?MD2.phases[s.phase]:'Preparación'}
function renderHeroTabs(){const b=$('heroTabs');if(!s.confirmed){b.innerHTML='';return}b.innerHTML=`<button data-main="game">Partida</button>`+s.heroes.map((x,i)=>`<button data-hi="${i}" class="${i===s.active&&$('hero').classList.contains('active')?'activeHero':''}" style="--hero:${COLORS[x.cls]}">${x.name}</button>`).join('')+`<button data-main="rules">Reglas</button>`;b.querySelectorAll('[data-hi]').forEach(q=>q.onclick=()=>{s.active=+q.dataset.hi;save();render();tab('hero')});b.querySelectorAll('[data-main]').forEach(q=>q.onclick=()=>tab(q.dataset.main))}
function renderSetup(){
 const picker=$('classPicker');picker.innerHTML=Object.keys(C).map(k=>`<button class="classChoice" data-class="${k}" style="border-color:${COLORS[k]}">${C[k].label}</button>`).join('');
 picker.querySelectorAll('[data-class]').forEach(b=>b.onclick=()=>{picker.querySelectorAll('.classChoice').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');picker.dataset.selected=b.dataset.class});
 $('setupHeroes').innerHTML=s.heroes.map((x,i)=>`<div class="heroSetupRow" style="border-left:5px solid ${COLORS[x.cls]}"><div class="grid"><label>Clase<input value="${C[x.cls].label}" disabled></label><label>Nombre<input data-name="${i}" value="${x.name}"></label></div><button data-remove="${i}" class="danger top">Quitar</button></div>`).join('')||'<p class="muted">Aún no hay héroes.</p>';
 document.querySelectorAll('[data-name]').forEach(inp=>inp.onchange=()=>{s.heroes[+inp.dataset.name].name=inp.value||C[s.heroes[+inp.dataset.name].cls].label;save()});
 document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{s.heroes.splice(+b.dataset.remove,1);s.active=0;save();renderSetup()});
 $('setupStatus').textContent=s.confirmed?'Grupo confirmado.':'Todavía no has confirmado el grupo.';
}
function renderGame(){if(!$('round'))return;$('round').textContent=s.round;$('phase').textContent=MD2.phases[s.phase];$('dungeon').textContent=dungeon();$('darkPos').textContent=s.heroes.length?darkNow()[0]:'—';$('phaseHelp').textContent=phaseHelp();$('darkTrack').innerHTML=darkArr().map((x,i)=>`<div class="cell ${i===s.dark.i?'active':''}">${x[0]}</div>`).join('');$('darkEvent').textContent=`${s.dark.side==='front'?'Anverso':'Reverso'} · ${darkNow()[0]}: ${darkNow()[1]}`}
function renderHero(){
 if(!s.heroes.length){$('heroPage').innerHTML='<div class="card">Primero prepara el grupo.</div>';return}
 const x=h(),color=COLORS[x.cls];document.documentElement.style.setProperty('--hero',color);
 $('heroPage').innerHTML=`<div class="card heroHeader"><div class="row between"><div><h2>${x.name}</h2><small>${C[x.cls].label}</small></div><span class="badge">Nivel ${x.level}</span></div>
 <div class="stats top"><div><small>Vida</small><b>${x.hp}/${x.hpMax}</b></div><div><small>Maná</small><b>${x.mana}/${x.manaMax}</b></div><div><small>XP</small><b>${x.xp}</b></div><div><small>Acciones</small><b>${x.actions}</b></div><div><small>Zona</small><b>${x.zone==='dark'?'Oscuridad':'Luz'}</b></div><div><small>Habilidad pendiente</small><b>${pending(x)?'Sí':'No'}</b></div></div></div>
 <div class="sectionTabs"><button data-sec="summary" class="active">Resumen</button><button data-sec="skills">Habilidades</button><button data-sec="actions">Acciones</button><button data-sec="inventory">Inventario</button></div>
 <div id="sec-summary" class="heroSection active">${summaryHtml(x)}</div>
 <div id="sec-skills" class="heroSection">${skillsHtml(x)}</div>
 <div id="sec-actions" class="heroSection">${actionsHtml(x)}</div>
 <div id="sec-inventory" class="heroSection">${inventoryHtml(x)}</div>`;
 document.querySelectorAll('[data-sec]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-sec]').forEach(q=>q.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.heroSection').forEach(q=>q.classList.remove('active'));$('sec-'+b.dataset.sec).classList.add('active')});
 bindHero();
}
function summaryHtml(x){return`<div class="card"><h2>Estadísticas</h2><div class="row"><button id="hpDown">− Vida</button><button id="hpUp">+ Vida</button><button id="manaDown">− Maná</button><button id="manaUp">+ Maná</button><button id="toggleZone">Luz/Oscuridad</button></div><h3>Habilidad propia</h3><div class="passive">${C[x.cls].ability}</div><h3>Sombras</h3><div class="passive">${C[x.cls].shadow}</div></div><div class="card"><h2>Mecánica exclusiva</h2>${classHtml(x)}</div>`}
function classHtml(x){
 if(x.cls==='rogue')return`<div class="resource">Fichas en mano: <b>${x.rogue.hand}</b> · Gastadas: ${x.rogue.spent}<div class="row"><button id="rDraw">Robar ficha</button><button id="rSpend">Gastar ficha</button></div></div>`;
 if(x.cls==='ranger')return`<div class="resource">El mazo de Flechas se resuelve físicamente: Rápido, Certero o Fallido.</div>`;
 if(x.cls==='shaman')return`<div class="resource">${['fire','water','air','nature'].map(k=>`<div class="row"><span class="badge">${{fire:'🔥 Fuego',water:'💧 Agua',air:'💨 Aire',nature:'🌿 Naturaleza'}[k]} ${x.shaman[k]}/4</span><button data-el="${k}" data-d="-1">−</button><button data-el="${k}" data-d="1">+</button><button data-max="${k}">Máx.</button><button data-use="${k}" ${x.shaman.unlocked[k]?'disabled':''}>${x.shaman.unlocked[k]?'Activa':'Consumir'}</button></div>`).join('')}</div>`;
 if(x.cls==='paladin')return`<div class="resource">Consagraciones registradas: <b>${x.paladin.consecrations}</b><div class="row"><button id="conAdd">Consagrar (−1 maná)</button><button id="conRem">Retirar</button></div><small>Comprueba LdV y que la zona no tenga otra Consagración.</small></div><label class="top">Habilidad bendecida<select id="blessed"><option value="">Ninguna</option>${activeSkills(x).map(q=>`<option ${x.paladin.blessed===q.name?'selected':''}>${q.name}</option>`).join('')}</select></label>`;
 if(x.cls==='mage')return`<div class="talismanGrid">${x.mage.slots.map((q,i)=>`<div class="talismanSlot ${i===x.mage.amulet?'active':''}"><b>Cara ${i+1}</b><input data-slot="${i}" value="${q}"><small>${i===x.mage.amulet?'Activa':'Inactiva'}</small></div>`).join('')}</div><button id="rotateTalisman" class="top">Girar Talismán</button>`;
 return`<div class="resource">Furia: <b>${x.berserker.fury}/7</b><div class="row"><button id="fDown">−</button><button id="fUp">+</button></div></div><label class="top">Postura<select id="stance"><option>Furia Sangrienta</option><option>Temerario</option><option>Provocador</option></select></label>`;
}
function skillsHtml(x){let html='<div class="card"><h2>Elecciones</h2>';for(let n=1;n<=x.level;n++){let v=x.choices[n],locked=x.lockedChoices[n];if(locked)html+=`<div class="skill skillLocked"><b>Nivel ${n}</b><br>${v}<div class="inventoryActions"><button data-undo="${n}">Deshacer elección</button></div></div>`;else html+=`<div class="choiceBox"><label>Nivel ${n}<select data-choice="${n}"><option value="">Seleccionar</option>${skills(x).filter(q=>q.level<=n).map(q=>`<option value="${q.name}" ${v===q.name?'selected':''}>${q.name}</option>`).join('')}</select></label><button data-confirm="${n}" class="primary">Confirmar</button></div>`}html+='</div><div class="card"><h2>Habilidades activas</h2>'+activeSkills(x).map(q=>`<div class="skill">${q.name}</div>`).join('')+'</div>';return html}
function actionsHtml(x){return`<div class="card"><h2>Acciones del héroe</h2><div class="actions"><button id="moveAction">Movimiento</button><button id="attackAction">Ataque</button><button id="defenseAction">Defensa</button><button data-action="Recuperación">Recuperación</button><button data-action="Intercambiar y equipar">Intercambiar y equipar</button><button data-action="Usar objeto">Usar objeto</button><button id="finishTurn" class="primary">Finalizar turno</button></div><p id="actionMsg" class="notice">Elige una acción.</p></div>
 <div class="card"><h2>Movimiento</h2><p>PM disponibles: <b id="movePm">${x.move.pm||0}</b></p><div class="actions"><button data-move="move">Mover 1 zona</button><button data-move="door">Abrir puerta</button><button data-move="interact">Interactuar</button><button id="finishMove">Finalizar</button></div></div>
 <div class="card"><h2>Ataque</h2><div class="grid"><label>Tipo<select id="attackType"><option>Cuerpo a cuerpo</option><option>A distancia</option><option>Mágico</option></select></label><label>Dados<input id="heroDice"></label><label>Dados negros<input id="blackDice" type="number" value="0"></label><label>Secuaces restantes<input id="minions" type="number" value="1"></label></div><button id="resolveAttack" class="primary top">Mostrar recordatorios</button><div id="attackNotes" class="notice">Sin resolver.</div></div>
 <div class="card"><h2>Defensa</h2><div class="grid"><label>Dados azules<input id="blueDice"></label><label>Espadas enemigas<input id="enemySwords" type="number" value="0"></label><label>Escudos obtenidos<input id="defShields" type="number" value="0"></label></div><button id="resolveDefense" class="primary top">Aplicar defensa</button><div id="defenseNotes" class="notice">Sin resolver.</div></div>`}
function inventoryHtml(x){return`<div class="card"><h2>Registrar objeto</h2><div class="grid"><label>Nombre<input id="itemName"></label><label>Destino<select id="itemDest"><option value="equip">Equipar ahora</option><option value="inventory">Guardar</option></select></label></div><button id="addItem" class="top">Registrar</button></div><div class="card"><h2>Equipo e inventario</h2><div id="inventoryList">${inventoryRows(x)}</div></div>`}
function inventoryRows(x){let r=[];x.equipped.forEach((q,i)=>r.push(`<div class="inventoryItem"><b>Equipado:</b> ${q}<div class="inventoryActions"><button data-store="${i}">Guardar</button><button data-delete-e="${i}">Eliminar</button></div></div>`));x.inventory.forEach((q,i)=>r.push(`<div class="inventoryItem"><b>Inventario:</b> ${q}<div class="inventoryActions"><button data-equip="${i}">Equipar</button><button data-delete-i="${i}">Consumir/Eliminar</button></div></div>`));return r.join('')||'<p class="muted">Sin objetos.</p>'}
function bindHero(){const x=h();
 $('hpDown').onclick=()=>{x.hp=Math.max(0,x.hp-1);save();renderHero()};$('hpUp').onclick=()=>{x.hp=Math.min(x.hpMax,x.hp+1);save();renderHero()};$('manaDown').onclick=()=>{x.mana=Math.max(0,x.mana-1);save();renderHero()};$('manaUp').onclick=()=>{x.mana=Math.min(x.manaMax,x.mana+1);save();renderHero()};
 $('toggleZone').onclick=()=>{x.zone=x.zone==='dark'?'light':'dark';save();renderHero();if(x.zone==='dark')say('Estás en oscuridad. No olvides el dado de Oscuridad y la habilidad de Sombras.')};
 document.querySelectorAll('[data-choice]').forEach(q=>q.onchange=()=>{x.choices[+q.dataset.choice]=q.value||null;save()});
 document.querySelectorAll('[data-confirm]').forEach(b=>b.onclick=()=>{let n=+b.dataset.confirm,v=x.choices[n];if(!v)return alert('Selecciona una habilidad.');if(!confirm(`¿Confirmas ${v}? La elección será permanente y solo podrá cambiarse con Deshacer.`))return;x.lockedChoices[n]=true;log(`Habilidad bloqueada: ${v}.`);say(`${v} confirmada. Esta elección queda bloqueada.`);save();renderHero();advancePending()});
 document.querySelectorAll('[data-undo]').forEach(b=>b.onclick=()=>{let n=+b.dataset.undo;if(confirm('¿Deshacer esta elección?')){x.lockedChoices[n]=false;x.choices[n]=null;log(`Deshizo habilidad del nivel ${n}.`);save();renderHero()}});
 if(x.cls==='rogue'){$('rDraw').onclick=()=>{x.rogue.hand++;x.actions++;save();renderHero()};$('rSpend').onclick=()=>{if(!x.rogue.hand)return;x.rogue.hand--;x.rogue.spent++;save();renderHero()}};
 if(x.cls==='shaman'){document.querySelectorAll('[data-el]').forEach(b=>b.onclick=()=>{let k=b.dataset.el;x.shaman[k]=Math.max(0,Math.min(4,x.shaman[k]+ +b.dataset.d));save();renderHero()});document.querySelectorAll('[data-max]').forEach(b=>b.onclick=()=>{x.shaman[b.dataset.max]=4;save();renderHero()});document.querySelectorAll('[data-use]').forEach(b=>b.onclick=()=>{let k=b.dataset.use;if(x.shaman[k]<4)return alert('No está al máximo');x.shaman[k]=0;x.shaman.unlocked[k]=true;log(`Bendición de ${k} activada permanentemente.`);save();renderHero()})}
 if(x.cls==='paladin'){$('conAdd').onclick=()=>{if(x.mana<1)return alert('Necesitas 1 maná');x.mana--;x.paladin.consecrations++;log('Consagró gastando 1 maná.');say('Gastas 1 maná para consagrar. Comprueba la línea de visión y que la zona no tenga otra Consagración.');save();renderHero()};$('conRem').onclick=()=>{x.paladin.consecrations=Math.max(0,x.paladin.consecrations-1);save();renderHero()};$('blessed').onchange=e=>{x.paladin.blessed=e.target.value;save();if(e.target.value)say(`Has bendecido ${e.target.value} hasta el final de la ronda.`)}}
 if(x.cls==='mage'){document.querySelectorAll('[data-slot]').forEach(inp=>inp.onchange=()=>{x.mage.slots[+inp.dataset.slot]=inp.value||'Vacío';save()});$('rotateTalisman').onclick=()=>{x.mage.amulet=(x.mage.amulet+1)%4;let a=x.mage.slots[x.mage.amulet];save();renderHero();say(`Talismán girado. Activa: ${a}.`)}}
 if(x.cls==='berserker'){$('fDown').onclick=()=>{x.berserker.fury=Math.max(0,x.berserker.fury-1);save();renderHero()};$('fUp').onclick=()=>{x.berserker.fury=Math.min(7,x.berserker.fury+1);save();renderHero()};$('stance').value=x.berserker.stance;$('stance').onchange=e=>{x.berserker.stance=e.target.value;save()}}
 $('moveAction').onclick=()=>startAction('Movimiento');$('attackAction').onclick=()=>startAction('Ataque');$('defenseAction').onclick=()=>{document.querySelector('#resolveDefense').scrollIntoView({behavior:'smooth'})};document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>startAction(b.dataset.action));$('finishTurn').onclick=()=>{x.actions=0;save();renderHero();say('Turno finalizado.')};
 document.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>useMove(b.dataset.move));$('finishMove').onclick=()=>{x.move={on:false,pm:0};save();renderHero()};
 $('resolveAttack').onclick=resolveAttack;$('resolveDefense').onclick=resolveDefense;
 $('addItem').onclick=()=>{let n=$('itemName').value.trim();if(!n)return;($('itemDest').value==='equip'?x.equipped:x.inventory).push(n);log(`Registró ${n}.`);save();renderHero()};
 document.querySelectorAll('[data-store]').forEach(b=>b.onclick=()=>{let q=x.equipped.splice(+b.dataset.store,1)[0];x.inventory.push(q);save();renderHero()});document.querySelectorAll('[data-equip]').forEach(b=>b.onclick=()=>{let q=x.inventory.splice(+b.dataset.equip,1)[0];x.equipped.push(q);save();renderHero()});
 document.querySelectorAll('[data-delete-e]').forEach(b=>b.onclick=()=>{if(confirm('¿Eliminar objeto?')){x.equipped.splice(+b.dataset.deleteE,1);save();renderHero()}});document.querySelectorAll('[data-delete-i]').forEach(b=>b.onclick=()=>{if(confirm('¿Consumir o eliminar objeto?')){x.inventory.splice(+b.dataset.deleteI,1);save();renderHero()}});
}
function advancePending(){let i=s.heroes.findIndex(q=>pending(q));if(i>=0){s.active=i;save();renderHero();renderHeroTabs();tab('hero');setTimeout(()=>document.querySelector('[data-sec="skills"]').click(),30);say(`Ahora debes elegir la habilidad de ${s.heroes[i].name}.`)}else{say('Todos los héroes tienen su habilidad inicial. La preparación ha terminado.');tab('game')}}
function startAction(name){const x=h();if(pending(x))return alert('Debes confirmar la habilidad pendiente.');if(s.phase!==0)return alert('Solo durante la Fase de Héroes.');if(x.actions<=0)return alert('No quedan acciones.');if(x.cls==='rogue'){if(!x.rogue.hand)return alert('No quedan fichas.');if(!confirm(`¿Gastar una ficha para ${name}?`))return;x.rogue.hand--;x.rogue.spent++}x.actions--;if(name==='Movimiento')x.move={on:true,pm:(x.cls==='ranger'?3:2)+(x.cls==='shaman'&&x.shaman.unlocked.air?1:0)};save();renderHero();say(x.actions===0?`${name}. No quedan acciones.`:`${name}. Te quedan ${x.actions} acciones.`)}
function useMove(k){const x=h();if(!x.move.on||!x.move.pm)return;x.move.pm--;log(k==='move'?'Se movió una zona.':k==='door'?'Abrió una puerta.':'Interactuó.');if(!x.move.pm)x.move.on=false;save();renderHero()}
function resolveAttack(){const x=h(),notes=[];if(x.zone==='dark')notes.push('Añade el dado de Oscuridad y aplica Sombras.');activeSkills(x).forEach(q=>notes.push(`Habilidad activa: ${q.name}.`));notes.push(`Habilidad propia: ${C[x.cls].ability}`);$('attackNotes').innerHTML='<ol>'+notes.map(q=>`<li>${q}</li>`).join('')+'</ol>'}
function resolveDefense(){const x=h(),w=Math.max(0,(+$('enemySwords').value||0)-(+$('defShields').value||0));x.hp=Math.max(0,x.hp-w);let t=`Recibes ${w} herida(s).`;if(x.cls==='berserker'&&w>0){let g=Math.min(w,7-x.berserker.fury);if(g>0&&confirm(`¿Convertir ${g} heridas en Furia?`)){x.berserker.fury+=g;t+=` Ganas ${g} Furia.`}}$('defenseNotes').textContent=t;log(t);save();renderHero();say(t)}
function renderHistory(){$('history').innerHTML=s.history.length?s.history.map(x=>`<div><b>Ronda ${x.r} · ${x.p} · ${x.n}</b><br>${x.t}</div>`).join(''):'<p class="muted">Sin registros.</p>'}
function nextPhase(){if(!s.confirmed)return alert('Primero prepara el grupo.');s.phaseHistory.push({p:s.phase,r:s.round,d:{...s.dark}});if(s.phase<3)s.phase++;else{advanceDark(false);s.phase=0;s.round++;s.heroes.forEach(x=>{x.actions=3;if(x.cls==='paladin'&&x.paladin.blessed){let old=x.paladin.blessed;x.paladin.blessed='';say(`${x.name}: retira la habilidad bendecida ${old}; vuelve a su lado normal.`)}})}log(`Comienza ${MD2.phases[s.phase]}.`);save();render();say(phaseHelp())}
function advanceDark(voice=true){if(s.dark.side==='front'){if(s.dark.i<8)s.dark.i++;else{s.dark.side='back';s.dark.i=0}}else s.dark.i=(s.dark.i+1)%4;let t=`Oscuridad ${darkNow()[0]}. ${darkNow()[1]}`;log(t);if(voice)say(t);save();renderGame()}
function award(kind){const before=s.heroes.map(x=>x.xp);if(kind==='m')h().xp++;if(kind==='l')s.heroes.forEach(x=>x.xp+=2);if(kind==='r')s.heroes.forEach(x=>x.xp+=4);s.xpHistory.push(before);save();render()}
function answerRule(q){q=q.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');if(q.includes('linea')&&q.includes('vision')||q.includes('ldv'))return MD2.rules['linea de vision'];if(q.includes('puerta'))return MD2.rules.puertas;if(q.includes('defensa'))return MD2.rules.defensa;if(q.includes('movimiento'))return MD2.rules.movimiento;if(q.includes('inventario')||q.includes('equipar'))return MD2.rules.inventario;if(q.includes('oscuridad'))return MD2.rules.oscuridad;if(q.includes('experiencia'))return MD2.rules.experiencia;if(q.includes('ataque'))return MD2.rules.ataque;return'No encontré una coincidencia exacta. Incluye el nombre de la carta o usa un tema rápido.'}
$('addSelectedClass').onclick=()=>{let k=$('classPicker').dataset.selected;if(!k)return alert('Selecciona una clase.');if(s.heroes.some(x=>x.cls===k))return alert('Esa clase ya está en el grupo.');s.heroes.push(makeHero(k));save();renderSetup()};
$('confirmGroup').onclick=()=>{if(!s.heroes.length)return alert('Añade al menos un héroe.');s.confirmed=true;s.active=0;save();render();say('Grupo confirmado. Ahora debes elegir la habilidad inicial de cada héroe.');advancePending()};
$('nextPhase').onclick=nextPhase;$('undoPhase').onclick=()=>{let q=s.phaseHistory.pop();if(!q)return;s.phase=q.p;s.round=q.r;s.dark=q.d;save();render()};$('advanceDark').onclick=()=>advanceDark();$('rewindDark').onclick=()=>{if(s.dark.side==='back'&&s.dark.i===0){s.dark.side='front';s.dark.i=8}else s.dark.i=Math.max(0,s.dark.i-1);save();renderGame()};
$('minionXp').onclick=()=>award('m');$('leaderXp').onclick=()=>award('l');$('roamerXp').onclick=()=>award('r');$('undoXp').onclick=()=>{let a=s.xpHistory.pop();if(a)s.heroes.forEach((x,i)=>x.xp=a[i]);save();render()};
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>tab(b.dataset.tab));
$('ask').onclick=()=>{window.lastAnswer=answerRule($('question').value);$('answer').textContent=window.lastAnswer};$('read').onclick=()=>say(window.lastAnswer||$('answer').textContent);$('dictate').onclick=()=>{let R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return alert('Dictado no disponible.');let r=new R();r.lang='es-ES';r.onresult=e=>{$('question').value=e.results[0][0].transcript;$('ask').click()};r.start()};document.querySelectorAll('[data-topic]').forEach(b=>b.onclick=()=>{$('question').value=b.dataset.topic;$('ask').click()});
$('clearHistory').onclick=()=>{s.history=[];save();renderHistory()};$('voice').onchange=e=>{s.voice=e.target.value;save()};$('rate').onchange=e=>{s.rate=e.target.value;save()};$('testVoice').onclick=()=>say('Asistente preparado.');
$('export').onclick=()=>{let b=new Blob([JSON.stringify(s,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='md2_alpha071.json';a.click()};$('import').onchange=e=>{let f=e.target.files[0],r=new FileReader();r.onload=()=>{try{s=JSON.parse(r.result);save();render()}catch{alert('Archivo no válido')}};if(f)r.readAsText(f)};$('newGame').onclick=()=>{if(confirm('¿Nueva partida?')){s=fresh();save();render();tab('setup')}};
render();